#!/bin/sh
#
# Automatically add branch name and branch description to every commit message except merge commit.
#

COMMIT_EDITMSG=$1

addBranchName() {
  NAME=$(git branch | grep '*' | sed 's/* //') 
  DESCRIPTION=$(git config branch."$NAME".description)
  DATE="$(date +%b) $(date +%y)"
  echo "[$NAME] ($DATE): $(cat $COMMIT_EDITMSG)" > $COMMIT_EDITMSG
  if [ -n "$DESCRIPTION" ] 
  then
     echo "" >> $COMMIT_EDITMSG
     echo $DESCRIPTION >> $COMMIT_EDITMSG
  fi 
}

IS_MERGE=$(cat $COMMIT_EDITMSG|grep -i 'merge'|wc -l)
IS_AMEND=$(ps -ocommand= -p $PPID | grep -e '--amend')

if [[ $IS_MERGE -eq 0 && $IS_AMEND -eq 0 ]]; then
  addBranchName
fi